name: Python UV Setup
description: Setup python environment and dependencies using uv

inputs:
  python-version:
    description: 'Python version to use (e.g., 3.13, 3.14)'
    required: true

  uv-lock-file:
    description: 'Path to the uv.lock file'
    required: false
    default: uv.lock

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen --dev
